import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ProtectedRoute } from "@/src/components/ProtectedRoute"
import "@/src/app/globals.css";
import { TooltipProvider } from "@/src/components/ui/tooltip";
import { Toaster } from "@/src/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Code",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProtectedRoute>
          <TooltipProvider>
            {children}
            <Toaster />
          </TooltipProvider>
        </ProtectedRoute>
      </body>
    </html>
  );
}
